#!/usr/bin/env python3
"""Generate paper-ready LaTeX tables from validated evaluation source tables.

This post-processing utility deliberately lives outside ``src/pzr`` so table
layout changes do not invalidate completed scientific cell manifests.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import math
from pathlib import Path
from typing import Callable, Iterable, Mapping, Sequence


METHODS = (
    "girard",
    "scott",
    "pca",
    "combastel",
    "mpc_terminal_beam",
    "mpc_terminal_beam_predictive_linear",
    "mpc_terminal_full_width",
    "pairwise_ranking_policy",
)
METHOD_LABELS = {
    "girard": "Girard",
    "scott": "Scott",
    "pca": "PCA",
    "combastel": "Combastel",
    "mpc_terminal_beam": "Terminal beam (offline)",
    "mpc_terminal_beam_predictive_linear": "Terminal beam (linear)",
    "mpc_terminal_full_width": "Full-width teacher",
    "mpc_cumulative_beam": "Cumulative beam (offline)",
    "pairwise_ranking_policy": "Pairwise ranking policy",
}
BUDGETS = (40, 80, 120, 150, 200, 250, 500)
CONDITIONS = (
    ("nominal", "Nominal"),
    ("drift", "Drift"),
    ("geofence", "Geofence"),
    ("drift_geofence", "Drift + geofence"),
)


def _read_csv(path: Path) -> list[dict[str, str]]:
    if not path.is_file():
        raise ValueError(f"source table is missing: {path}")
    with path.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def _float(value: object) -> float:
    try:
        return float(value)
    except (TypeError, ValueError):
        return math.nan


def _finite(value: object) -> bool:
    return math.isfinite(_float(value))


def _percent(value: object) -> str:
    number = _float(value)
    return f"{100.0 * number:.2f}\\%" if math.isfinite(number) else "--"


def _scientific(value: object) -> str:
    number = _float(value)
    return f"{number:.2e}" if math.isfinite(number) else "--"


def _number(value: object) -> str:
    number = _float(value)
    return f"{number:.3g}" if math.isfinite(number) else "--"


def _integer(value: object) -> str:
    number = _float(value)
    return str(int(number)) if math.isfinite(number) else "--"


def _interval(
    center: object,
    low: object,
    high: object,
    formatter: Callable[[object], str],
) -> str:
    values = formatter(center), formatter(low), formatter(high)
    return "--" if "--" in values else f"{values[0]} [{values[1]}, {values[2]}]"


def _tex(value: object) -> str:
    return (
        str(value)
        .replace("\\", "\\textbackslash{}")
        .replace("_", "\\_")
        .replace("%", "\\%")
        .replace("&", "\\&")
    )


def _index(
    rows: Sequence[Mapping[str, str]],
    keys: Sequence[str],
    *,
    expected_count: int,
    label: str,
) -> dict[tuple[str, ...], Mapping[str, str]]:
    if len(rows) != expected_count:
        raise ValueError(f"{label} has {len(rows)} rows, expected {expected_count}")
    result: dict[tuple[str, ...], Mapping[str, str]] = {}
    for row in rows:
        key = tuple(row[name] for name in keys)
        if key in result:
            raise ValueError(f"{label} has duplicate cell {key}")
        result[key] = row
    return result


def _table(lines: Iterable[str]) -> str:
    return "\n".join((
        "% Generated by tools/generate_paper_tables.py; do not edit.",
        *lines,
        "",
    ))


def _nominal_table(rows: Sequence[Mapping[str, str]]) -> str:
    cells = _index(
        rows,
        ("budget", "method"),
        expected_count=len(BUDGETS) * len(METHODS),
        label="nominal generalization",
    )
    lines = [
        "\\begin{tabular}{rllrrrrrl}",
        "\\toprule",
        (
            "Budget & Method & Macro FPR [95\\% CI] & Pooled FPR & "
            "Median FPR [IQR] & Mean loss & Median loss [IQR] & "
            "Valid/failed & Fallback \\\\"
        ),
        "\\midrule",
    ]
    for budget in BUDGETS:
        for method_index, method in enumerate(METHODS):
            row = cells[(str(budget), method)]
            budget_label = str(budget) if method_index == 0 else ""
            lines.append(
                f"{budget_label} & {_tex(METHOD_LABELS[method])} & "
                f"{_interval(row['macro_fpr'], row['macro_fpr_ci_low'], row['macro_fpr_ci_high'], _percent)} & "
                f"{_percent(row['pooled_fpr'])} & "
                f"{_interval(row['median_fpr'], row['fpr_iqr_low'], row['fpr_iqr_high'], _percent)} & "
                f"{_scientific(row['macro_mean_approx_loss'])} & "
                f"{_interval(row['median_mean_approx_loss'], row['loss_iqr_low'], row['loss_iqr_high'], _scientific)} & "
                f"{_integer(row['valid_count'])}/{_integer(row['failed_count'])} & "
                f"{_percent(row['fallback_rate'])} \\\\"
            )
    lines.extend(("\\bottomrule", "\\end{tabular}"))
    return _table(lines)


def _headline_table(rows: Sequence[Mapping[str, str]]) -> str:
    cells = _index(
        rows,
        ("budget", "method"),
        expected_count=len(BUDGETS) * len(METHODS),
        label="fixed figure-eight headline",
    )
    include_timing = any(
        _finite(row[f"{prefix}_throughput"])
        for row in rows
        for prefix, _ in CONDITIONS
    )
    metrics_per_condition = 3 if include_timing else 2
    lines = [
        "\\begin{tabular}{ll" + "r" * metrics_per_condition * len(CONDITIONS) + "}",
        "\\toprule",
        "Budget & Method & "
        + " & ".join(
            f"\\multicolumn{{{metrics_per_condition}}}{{c}}{{{label}}}"
            for _, label in CONDITIONS
        )
        + " \\\\",
        " & & "
        + " & ".join(
            "FPR (\\%) & Loss & Events/s"
            if include_timing else "FPR (\\%) & Loss"
            for _ in CONDITIONS
        )
        + " \\\\",
        "\\midrule",
    ]
    for budget in BUDGETS:
        for method_index, method in enumerate(METHODS):
            row = cells[(str(budget), method)]
            values: list[str] = []
            for prefix, _ in CONDITIONS:
                values.extend((
                    _percent(row[f"{prefix}_fpr"]),
                    _scientific(row[f"{prefix}_loss"]),
                ))
                if include_timing:
                    values.append(_number(row[f"{prefix}_throughput"]))
            budget_label = str(budget) if method_index == 0 else ""
            lines.append(
                f"{budget_label} & {_tex(METHOD_LABELS[method])} & "
                + " & ".join(values)
                + " \\\\"
            )
    lines.extend(("\\bottomrule", "\\end{tabular}"))
    return _table(lines)


def _objective_table(rows: Sequence[Mapping[str, str]]) -> str:
    cells = _index(
        rows,
        ("condition", "budget", "method"),
        expected_count=4 * len(BUDGETS) * 2,
        label="objective comparison",
    )
    condition_order = (
        "figure8",
        "figure8_drift",
        "figure8_geofence",
        "figure8_drift_geofence",
    )
    methods = ("mpc_terminal_beam", "mpc_cumulative_beam")
    lines = [
        "\\begin{tabular}{lrllrr}",
        "\\toprule",
        "Condition & Budget & Objective & Available & Macro FPR (\\%) & Mean loss \\\\",
        "\\midrule",
    ]
    for condition in condition_order:
        for budget in BUDGETS:
            for method in methods:
                row = cells[(condition, str(budget), method)]
                lines.append(
                    f"{_tex(condition)} & {budget} & "
                    f"{_tex(METHOD_LABELS[method])} & "
                    f"{'yes' if row['available'].lower() == 'true' else 'no'} & "
                    f"{_percent(row['macro_fpr'])} & "
                    f"{_scientific(row['macro_mean_approx_loss'])} \\\\"
                )
    lines.extend(("\\bottomrule", "\\end{tabular}"))
    return _table(lines)


def _ablation_table(rows: Sequence[Mapping[str, str]]) -> str:
    cells = _index(
        rows,
        ("horizon", "beam_width"),
        expected_count=16,
        label="H/W ablation",
    )
    lines = [
        "\\begin{tabular}{rrrrrll}",
        "\\toprule",
        "Horizon & Width & Macro FPR (\\%) & Mean loss & Events/s & Valid/failed & H4/W4 \\\\",
        "\\midrule",
    ]
    for horizon in (1, 2, 4, 8):
        for width in (1, 2, 4, 8):
            row = cells[(str(horizon), str(width))]
            lines.append(
                f"{horizon} & {width} & {_percent(row['macro_fpr'])} & "
                f"{_scientific(row['mean_loss'])} & "
                f"{_number(row['median_throughput_events_per_second'])} & "
                f"{_integer(row['valid_count'])}/{_integer(row['failed_count'])} & "
                f"{'yes' if row['highlight_default'].lower() == 'true' else ''} \\\\"
            )
    lines.extend(("\\bottomrule", "\\end{tabular}"))
    return _table(lines)


def _fallback_table(rows: Sequence[Mapping[str, str]]) -> str:
    _index(
        rows,
        ("condition", "budget", "method"),
        expected_count=4 * len(BUDGETS),
        label="fallback diagnostics",
    )
    lines = [
        "\\begin{tabular}{llrlrr}",
        "\\toprule",
        "Condition & Method & Budget & State & First event & Completed \\\\",
        "\\midrule",
    ]
    for row in rows:
        lines.append(
            f"{_tex(row['condition'])} & "
            f"{_tex(METHOD_LABELS.get(row['method'], row['method']))} & "
            f"{_integer(row['budget'])} & {_tex(row['status'])} & "
            f"{_integer(row['first_fallback_event'])} & "
            f"{_percent(row['completed_fraction'])} \\\\"
        )
    lines.extend(("\\bottomrule", "\\end{tabular}"))
    return _table(lines)


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    digest.update(path.read_bytes())
    return digest.hexdigest()


def _write(path: Path, text: str) -> None:
    temporary = path.with_suffix(path.suffix + ".tmp")
    temporary.write_text(text, encoding="utf-8")
    temporary.replace(path)


def generate(source: Path, output: Path) -> None:
    output.mkdir(parents=True, exist_ok=True)
    sources = {
        "nominal": source / "nominal_generalization_aggregates.csv",
        "headline": source / "headline_long_table.csv",
        "objective": source / "objective_comparison.csv",
        "ablation": source / "ablation_heatmaps.csv",
        "fallback": source / "fallback_diagnostics.csv",
    }
    outputs = {
        "nominal_generalization_table.tex": _nominal_table(
            _read_csv(sources["nominal"]),
        ),
        "fixed_figure8_headline_table.tex": _headline_table(
            _read_csv(sources["headline"]),
        ),
        "objective_comparison_table.tex": _objective_table(
            _read_csv(sources["objective"]),
        ),
        "ablation_table.tex": _ablation_table(
            _read_csv(sources["ablation"]),
        ),
        "fallback_diagnostics_table.tex": _fallback_table(
            _read_csv(sources["fallback"]),
        ),
    }
    for name, text in outputs.items():
        _write(output / name, text)
    manifest = {
        "schema": "pzr.paper-latex-tables.v1",
        "source_directory": str(source),
        "source_sha256": {
            path.name: _sha256(path) for path in sources.values()
        },
        "table_sha256": {
            name: _sha256(output / name) for name in outputs
        },
    }
    _write(
        output / "table_hashes.json",
        json.dumps(manifest, indent=2, sort_keys=True) + "\n",
    )


def main() -> None:
    root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(
        description="Generate paper-ready TeX tables from validated source CSVs",
    )
    parser.add_argument(
        "--source",
        type=Path,
        default=root / "results/paper-evaluation-v3/science-report/artifacts",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=root / "results/paper-evaluation-v3/paper-tables",
    )
    args = parser.parse_args()
    generate(args.source.resolve(), args.output.resolve())
    print(f"Generated LaTeX tables in {args.output.resolve()}")


if __name__ == "__main__":
    main()
